# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zeroplayergame',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.ZeroPlayerGame'),
        ),
        migrations.AddField(
            model_name='zeroplayergame',
            name='required_modules',
            field=models.ManyToManyField(to='game.CodeModule'),
        ),
        migrations.AddField(
            model_name='seedvectorparam',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_vectorparams', to='game.ZeroPlayerGame'),
        ),
        migrations.AddField(
            model_name='seedvectorparam',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectorparams', to='game.GameInstance'),
        ),
        migrations.AddField(
            model_name='savedfunction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedFunctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameinstancesnapshot',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.GameInstance'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='game.ZeroPlayerGame'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='instantiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.Category'),
        ),
    ]
